Updating form section to track active question/section.
uwblueprint/cookie-monster pull request #226
Opened 2020-10-15 02:33 UTC by ahmedhamodi

Subtasks completed:
- track active question/section
- dynamically loading in the questions inside of a section.
- set up the template functions for how to integrate with the schema
- update schema to include title, description, and created_by

2020-10-15 23:27 UTC, GodGreg approved these changes

2020-10-15 23:30 UTC, GodGreg commented
@xinhaoz Review please. 

Also I know you'll catch the form ID in the form creation url. It is currently not being used to load anything. 

But we may use it later so that it sets the users program on load if the is a valid program ID is in the url

2020-10-20 00:13 UTC, xinhaoz requested changes

2020-10-20 00:13 UTC, xinhaoz commented on src/Components/FormCreation/CreateEditForm.js
> +              <FormCard
I think we should be rendering questions as a child of FormSection component

2020-10-20 00:13 UTC, xinhaoz commented on src/Components/FormCreation/CreateEditForm.js
> +                active={activeSection === key && activeQuestion === questionKey}
Once we render the questions inside FormSection, we can move the active question logic to form section as well and set the active question by whether or not the current section is active.

2020-10-20 01:28 UTC, GodGreg approved these changes

2020-10-23 02:02 UTC, xinhaoz approved these changes
LGTM!! Let's remember to change formId to programId

2020-10-23 20:37 UTC, merged