Gromm/delete form sections2
uwblueprint/cookie-monster pull request #257
Opened 2020-11-13 02:36 UTC by guy-ro

Added functionality to delete form sections. 

Added Greg's fix to the form model.

Still missing undo deletes.

2020-11-13 18:51 UTC, GodGreg requested changes
The CSS of the dialog does not match the figma

![image](https://user-images.githubusercontent.com/30921670/99109512-f20ac600-25b6-11eb-9a7c-fb544735d7fa.png)
vs 
![image](https://user-images.githubusercontent.com/30921670/99109481-e7503100-25b6-11eb-8545-32b97ec4a59b.png)

Please see ticket for Figma links. On Figma, you can hover over an element and it will show you its dimensions and the distance is it from other objects. As well the CSS is generated on the right-hand side (which you can pretty much just copy/paste)

2020-11-13 18:51 UTC, GodGreg commented on src/Components/FormCreation/CreateEditForm.js
> +import DeleteSectionConfirmation from "./DeleteSectionConfirmation";
remove unused imports

2020-11-13 21:45 UTC, guy-ro commented
Thanks Greg! Didn't know you could do that with Figma cause it only shows you those tools if you log in.

Updated the style to that shown in Figma.

For the unused imports, I commented out those that I was using in implementing the undo delete feature.

2020-11-15 20:11 UTC, GodGreg commented
> Thanks Greg! Didn't know you could do that with Figma cause it only shows you those tools if you log in.
> 
> Updated the style to that shown in Figma.
> 
> For the unused imports, I commented out those that I was using in implementing the undo delete feature. Do you want me to remove them in addition to commenting them out?

Its fine if used for the undo-delete feature

2020-11-17 00:14 UTC, GodGreg approved these changes

2020-11-17 00:14 UTC, merged